/*
 * This repository defines the services for ingredient actions.
 * This includes saving and updating them.
 */

using Flavor_Forge.Entities;
using Flavor_Forge.Services.Service;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Flavor_Forge.Services.Repository
{
    public class IngredientRepository : IIngredientServices
    {
        private readonly Flavor_ForgeDBContext _flavor_forgeDBContext;

        public IngredientRepository(Flavor_ForgeDBContext context)
        {
            _flavor_forgeDBContext = context;
        }

        // Acquire ingredient by Id
        public List<Ingredient> GetIngredients(int recipeId)
        {
            return _flavor_forgeDBContext.Ingredients
                .Where(i => i.RecipeId == recipeId)
                .ToList();
        }

        // Add new ingrdient to ingredient database
        public Ingredient SaveIngredient(Ingredient ingredient)
        {
            // When ingredient and added an id is autogenerated
            _flavor_forgeDBContext.Ingredients.Add(ingredient);
            _flavor_forgeDBContext.SaveChanges();
            return ingredient;
        }

        // Save a list of ingredients so that they can be stored together for recipes
        public void SaveIngredients(List<Ingredient> ingredients, int recipeId)
        {
            // Check that ingredient list is not empty
            if (ingredients == null || !ingredients.Any())
            {
                throw new ArgumentException("Ingredients list cannot be null or empty.");
            }

            foreach (var ingredient in ingredients)
            {
                // Check that ingredient is not null
                if (ingredient != null && !string.IsNullOrEmpty(ingredient.IngredientName))
                {
                    // Assign this ingredient with its corresponding id from database and then add it to the ingredient list
                    ingredient.RecipeId = recipeId;
                    _flavor_forgeDBContext.Ingredients.Add(ingredient);
                }
            }

            _flavor_forgeDBContext.SaveChanges();
        }

        // Update a list of ingredients saved in database
        public async Task UpdateIngredients(List<Ingredient> ingredients, int recipeId)
        {
            if (ingredients == null || !ingredients.Any())
            {
                throw new ArgumentException("Ingredients list cannot be null or empty.");
            }

            // Fetch all existing ingredients for the recipe
            var existingIngredients = _flavor_forgeDBContext.Ingredients
                .Where(i => i.RecipeId == recipeId)
                .ToList();

            // Remove all existing ingredients for the recipe
            _flavor_forgeDBContext.Ingredients.RemoveRange(existingIngredients);

            // Add the new ingredients
            foreach (var ingredient in ingredients)
            {
                ingredient.RecipeId = recipeId; // Ensure the RecipeId is set for each ingredient
                _flavor_forgeDBContext.Ingredients.Add(ingredient);
            }

            // Save changes to the database
            await _flavor_forgeDBContext.SaveChangesAsync();
        }

    }
}
