/*
 * This repository defines the services for user handling.
 * This includes actions for creating or deleting them.
 */

using Flavor_Forge.Entities;
using Flavor_Forge.Services.Service;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Flavor_Forge.Services.Repository
{
    public class UserRepository : IUserServices
    {
        private readonly Flavor_ForgeDBContext _flavor_forgeDBContext;
        public UserRepository(Flavor_ForgeDBContext context)
        {
            _flavor_forgeDBContext = context;
        }

        // Return all saved users
        public List<User> GetUsers()
        {
            return _flavor_forgeDBContext.Users.ToList();
        }

        // Return User from database whose id matches
        public User GetUser(int userId)
        {
            return _flavor_forgeDBContext.Users.FirstOrDefault(e => e.UserId == userId);
        }

        public User CreateUser(User user)
        {
            // Add created user to database with the autogenerated id
            _flavor_forgeDBContext.Users.Add(user);
            _flavor_forgeDBContext.SaveChanges();
            return user;
        }

        public User UpdateUser(User user)
        {
            // Checks all attributes of user and updates the changed ones
            _flavor_forgeDBContext.Users.Update(user);
            _flavor_forgeDBContext.SaveChanges();
            return user;
        }

        // Removes User from database and leaves a return message
        public string DeleteUser(int userId)
        {
            // Uses GetUser function to find then remove user using its id 
            _flavor_forgeDBContext.Users.Remove(GetUser(userId));
            _flavor_forgeDBContext.SaveChanges();
            return "User deleted";
        }
    }
}
